name: Auto Update News

permissions:
  contents: write  # 자동 커밋/푸시 권한

on:
  schedule:
    - cron: '*/30 * * * *'  # 30분마다 실행
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v3

      - name: Python 설치
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 뉴스 HTML 생성
        run: python generate_news.py

      - name: 변경사항 커밋 및 푸시
        run: |
          git config --local user.name "goma-news"
          git config --local user.email "bot@goma.com"
          git add goma_news_live_updated.html
          git commit -m "자동 업데이트: 뉴스 갱신" || echo "No changes to commit"
          git push

